#!/bin/bash

ICON_PATH=/usr/share/icons/pepi
BIN_PATH=/usr/local/bin

which apt-get 1> /dev/null 2>/dev/null
HAS_APT_GET=$?
which dnf 1> /dev/null 2>/dev/null
HAS_DNF=$?
which yum 1> /dev/null 2>/dev/null
HAS_YUM=$?


if [ "$HAS_APT_GET" -eq 0 ]; then
  sudo apt-get install libnotify-bin sound-theme-freedesktop -qy
elif [ "$HAS_DNF" -eq 0 ] || [ "$HAS_YUM" -eq 0 ]; then
  if [ "$HAS_DNF" -eq 0 ]; then
    sudo dnf install --assumeyes libnotify sound-theme-freedesktop
  else
    sudo yum install --assumeyes libnotify sound-theme-freedesktop
  fi
else
  echo "Unrecognized package manager! :("
  exit
fi

if [ ! -d $ICON_PATH ]
then
  sudo mkdir $ICON_PATH
fi

if [ ! -L $INSTALLED_ICON_PATH ]
then
  sudo ln -s "$(pwd)/icons/hourglass-small.png" $ICON_PATH
fi

if [ ! -L $BIN_PATH/pepi ]
then  
  sudo ln -s "$(pwd)/pepi" $BIN_PATH
fi

echo "pepi successfully installed!"
