#!/bin/bash

verify () {
  if [ $? != 0 ]; then
    echo "$1"
    exit 2
  fi
}

INFO_PATH=/usr/share/pepi/info
if [ -d $INFO_PATH ]
then
  version_file=$INFO_PATH/version.txt
  help_file=$INFO_PATH/help.txt
else
  version_file="$(pwd)/info/version.txt"
  help_file="$(pwd)/info/help.txt"
fi

pepi_help () {
  echo "Usage: pepi COMMAND"
  echo "  pepi will notify you when COMMAND finishes"
  echo "  and inform you whether it was successful, or failed."
  exit
}

version () {
  cat $version_file
  exit
}


while [ "$#" -gt 0 ]; do
  if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    pepi_help
  elif [ "$1" == "-v" ] || [ "$1" == "--version" ]; then
    version
  elif [ "$1" == "--" ]; then
    shift
    break
  else
    break
  fi
done


INSTALLED_ICON_PATH=/usr/share/icons/pepi/hourglass-small.png
if [ -f $INSTALLED_ICON_PATH ]
then
  small_icon=$INSTALLED_ICON_PATH
else
  small_icon="$(pwd)/icons/hourglass-small.png"
fi

default_success_message="Your job is done! =)"
default_error_message="Your job failed! =("

error_sound_file="/usr/share/sounds/freedesktop/stereo/suspend-error.oga"
success_sound_file="/usr/share/sounds/freedesktop/stereo/complete.oga"
sound_files=($success_sound_file $error_sound_file)

for file in $sound_files
do
  if [ ! -f "$file" ]
  then
    echo $file
    echo "Cannot find the required sound files. You need to install the sound-theme-freedesktop package"
    exit 3
  fi
done

notify () {
  if [ $? != 0 ]; then
    notify-send "$default_error_message" --icon=$small_icon --hint=string:sound-file:$error_sound_file
    exit 4
  else
    notify-send "$default_success_message" --icon=$small_icon --hint=string:sound-file:$success_sound_file
    exit 0
  fi
}

# Verify dependencies
notify-send --version > /dev/null
verify "Cannot find notify-send. You need to install the libnotify-bin package"


if (( "$#" == 0 ))
then
  echo "Pepi need a command to run, please pass a command as argument"
  exit 1
else
  eval "$@"
  notify
fi
