#!/bin/bash

verify () {
  if [ $? != 0 ]; then
    echo "$1"
    exit 2
  fi
}

default_success_message="Your job is done! =)"
default_error_message="Your job failed! =("

error_sound_file="/usr/share/sounds/freedesktop/stereo/suspend-error.oga"
success_sound_file="/usr/share/sounds/freedesktop/stereo/complete.oga"
sound_files=($success_sound_file $error_sound_file)

for file in $sound_files
do
  if [ ! -f "$file" ]
  then
    echo $file
    echo "Cannot find the required sound files. You need to install the sound-theme-freedesktop package"
    exit 3
  fi
done

notify_with_sound () {
  if [ $? != 0 ]; then
    notify-send "$default_error_message" --urgency=critical --hint=string:sound-file:$error_sound_file
    exit 4
  else
    notify-send "$default_success_message" --hint=string:sound-file:$success_sound_file
    exit 0
  fi
}

# Verify dependencies
notify-send --version > /dev/null
verify "Cannot find notify-send. You need to install the libnotify-bin package"


if (( "$#" == 0 ))
then
  echo "Pepi need a command to run, please pass a command as argument"
  exit 1
else
  eval "$@"
  notify_with_sound
fi
